<?php

use Illuminate\Database\Seeder;
use App\ajar;
use App\dosen;
use App\lab;
use App\mhs;
use App\mk;
use App\User;
class DummySeeder extends Seeder
{
    public function run()
    {
        $i=0;
        
        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="0";
        $use->pertanyaan2="21";
        $use->pertanyaan3="33";
        $use->pertanyaan4="46";
        $use->pertanyaan5="64";
        $use->pertanyaan6="85";
        $use->pertanyaan7="109";
        $use->pertanyaan8="128";
        $use->pertanyaan9="160";
        $use->pertanyaan10="162";
        $use->pertanyaan11="88";
        $use->pertanyaan12="53";
        $use->pertanyaan13="2";
        $use->pertanyaan14="100";
        $use->pertanyaan15="110";
        $use->save();
        $i++;
        
        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="39";
        $use->pertanyaan2="122";
        $use->pertanyaan3="146";
        $use->pertanyaan4="28";
        $use->pertanyaan5="73";
        $use->pertanyaan6="120";
        $use->pertanyaan7="140";
        $use->pertanyaan8="42";
        $use->pertanyaan9="59";
        $use->pertanyaan10="90";
        $use->pertanyaan11="15";
        $use->pertanyaan12="31";
        $use->pertanyaan13="117";
        $use->pertanyaan14="9";
        $use->pertanyaan15="107";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="49";
        $use->pertanyaan2="148";
        $use->pertanyaan3="35";
        $use->pertanyaan4="126";
        $use->pertanyaan5="1";
        $use->pertanyaan6="82";
        $use->pertanyaan7="45";
        $use->pertanyaan8="114";
        $use->pertanyaan9="11";
        $use->pertanyaan10="80";
        $use->pertanyaan11="94";
        $use->pertanyaan12="19";
        $use->pertanyaan13="25";
        $use->pertanyaan14="155";
        $use->pertanyaan15="69";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="93";
        $use->pertanyaan2="97";
        $use->pertanyaan3="5";
        $use->pertanyaan4="115";
        $use->pertanyaan5="44";
        $use->pertanyaan6="18";
        $use->pertanyaan7="23";
        $use->pertanyaan8="105";
        $use->pertanyaan9="57";
        $use->pertanyaan10="32";
        $use->pertanyaan11="40";
        $use->pertanyaan12="165";
        $use->pertanyaan13="79";
        $use->pertanyaan14="65";
        $use->pertanyaan15="131";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="13";
        $use->pertanyaan2="111";
        $use->pertanyaan3="129";
        $use->pertanyaan4="98";
        $use->pertanyaan5="103";
        $use->pertanyaan6="83";
        $use->pertanyaan7="72";
        $use->pertanyaan8="81";
        $use->pertanyaan9="43";
        $use->pertanyaan10="89";
        $use->pertanyaan11="60";
        $use->pertanyaan12="52";
        $use->pertanyaan13="157";
        $use->pertanyaan14="136";
        $use->pertanyaan15="156";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="95";
        $use->pertanyaan2="41";
        $use->pertanyaan3="112";
        $use->pertanyaan4="4";
        $use->pertanyaan5="133";
        $use->pertanyaan6="17";
        $use->pertanyaan7="20";
        $use->pertanyaan8="55";
        $use->pertanyaan9="36";
        $use->pertanyaan10="152";
        $use->pertanyaan11="50";
        $use->pertanyaan12="86";
        $use->pertanyaan13="78";
        $use->pertanyaan14="164";
        $use->pertanyaan15="63";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="84";
        $use->pertanyaan2="3";
        $use->pertanyaan3="47";
        $use->pertanyaan4="158";
        $use->pertanyaan5="34";
        $use->pertanyaan6="92";
        $use->pertanyaan7="27";
        $use->pertanyaan8="70";
        $use->pertanyaan9="106";
        $use->pertanyaan10="24";
        $use->pertanyaan11="119";
        $use->pertanyaan12="58";
        $use->pertanyaan13="7";
        $use->pertanyaan14="12";
        $use->pertanyaan15="141";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="125";
        $use->pertanyaan2="6";
        $use->pertanyaan3="135";
        $use->pertanyaan4="154";
        $use->pertanyaan5="113";
        $use->pertanyaan6="14";
        $use->pertanyaan7="104";
        $use->pertanyaan8="29";
        $use->pertanyaan9="151";
        $use->pertanyaan10="37";
        $use->pertanyaan11="56";
        $use->pertanyaan12="38";
        $use->pertanyaan13="91";
        $use->pertanyaan14="75";
        $use->pertanyaan15="66";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="108";
        $use->pertanyaan2="77";
        $use->pertanyaan3="163";
        $use->pertanyaan4="8";
        $use->pertanyaan5="10";
        $use->pertanyaan6="139";
        $use->pertanyaan7="68";
        $use->pertanyaan8="166";
        $use->pertanyaan9="48";
        $use->pertanyaan10="54";
        $use->pertanyaan11="62";
        $use->pertanyaan12="137";
        $use->pertanyaan13="30";
        $use->pertanyaan14="51";
        $use->pertanyaan15="22";
        $use->save();
        $i++;

        $use=new rooms;
        $use->id_room=$i;
        $use->pertanyaan1="16";
        $use->pertanyaan2="99";
        $use->pertanyaan3="26";
        $use->pertanyaan4="130";
        $use->pertanyaan5="116";
        $use->pertanyaan6="61";
        $use->pertanyaan7="67";
        $use->pertanyaan8="87";
        $use->pertanyaan9="96";
        $use->pertanyaan10="121";
        $use->pertanyaan11="142";
        $use->pertanyaan12="144";
        $use->pertanyaan13="74";
        $use->pertanyaan14="127";
        $use->pertanyaan15="71";
        $use->save();
        $i++;
    }
}
